# GAIRR Mobile PWA
server {
    listen 80;
    server_name 8.136.112.142;
    
    location = /app {
        return 302 /app/;
    }
    
    location /app/ {
        alias /var/www/gairr-mobile/;
        index index.html;
        try_files $uri $uri/ =404;
    }
}
